#!/usr/bin/env python

patch_list=[
  ["*otherLinuxGuest", "centos64Guest"],
  ["nat", "PIPAT-DEV-ROUTED"],
  ["<OperatingSystemSection", "<ovf:OperatingSystemSection"],
  ["<Envelope", "<ovf:Envelope"],
  ["<Description", "<ovf:Description"],
  ["<Disk", "<ovf:Disk"],
  ["<DiskSection", "<ovf:DiskSection"],
  ["<File", "<ovf:File"],
  ["<Info", "<ovf:Info"],
  ["<Name", "<ovf:Name"],
  ["<Network", "<ovf:Network"],
  ["<NetworkSection", "<ovf:NetworkSection"],
  ["<References", "<ovf:References"],
  ["<System", "<ovf:System"],
  ["<VirtualHardwareSection", "<ovf:VirtualHardwareSection"],
  ["<VirtualSystem", "<ovf:VirtualSystem"],
  ["<Info", "<ovf:Info"],
  ["<Item", "<ovf:Item"],
  ["</OperatingSystemSection", "</ovf:OperatingSystemSection"],
  ["</Envelope", "</ovf:Envelope"],
  ["</Description", "</ovf:Description"],
  ["</Disk", "</ovf:Disk"],
  ["</DiskSection", "</ovf:DiskSection"],
  ["</File", "</ovf:File"],
  ["</Info", "</ovf:Info"],
  ["</Name", "</ovf:Name"],
  ["</Network", "</ovf:Network"],
  ["</NetworkSection", "</ovf:NetworkSection"],
  ["</References", "</ovf:References"],
  ["</System", "</ovf:System"],
  ["</VirtualHardwareSection", "</ovf:VirtualHardwareSection"],
  ["</VirtualSystem", "</ovf:VirtualSystem"],
  ["</Info", "</ovf:Info"],
  ["</Item", "</ovf:Item"]
           ]

f=open('tmp.ovf/centos7/centos7.ovf','r')

print """<?xml version="1.0" encoding="UTF-8"?>
<!--Generated by VMware ovftool 4.2.0 (build-5965791), UTC time: 2017-08-19T10:58:36.43619Z-->
<ovf:Envelope vmw:buildId="build-4274667" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vcloud="http://www.vmware.com/vcloud/v1.5" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2.22.0/CIM_VirtualSystemSettingData.xsd http://www.vmware.com/schema/ovf http://www.vmware.com/schema/ovf http://schemas.dmtf.org/ovf/envelope/1 http://schemas.dmtf.org/ovf/envelope/1/dsp8023_1.1.0.xsd http://www.vmware.com/vcloud/v1.5 http://10.10.6.11/api/v1.5/schema/master.xsd http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2.22.0/CIM_ResourceAllocationSettingData.xsd">"""

lines=f.read().split("\n")

print_line=False

for l in lines:
  if "<References>" in l:
    print_line=True

  if print_line:
    for p in patch_list:
      l=l.replace(p[0],p[1])

    print l

    if "</ovf:NetworkSection>" in l:
      print '  <vcloud:CustomizationSection goldMaster="false" ovf:required="false">'
      print '      <ovf:Info>VApp template customization section</ovf:Info>'
      print '      <vcloud:CustomizeOnInstantiate>true</vcloud:CustomizeOnInstantiate>'
      print '  </vcloud:CustomizationSection>'

    if "</ovf:VirtualHardwareSection>" in l:
      print '    <vcloud:GuestCustomizationSection ovf:required="false">'
      print '        <ovf:Info>Specifies Guest OS Customization Settings</ovf:Info>'
      print '        <vcloud:Enabled>true</vcloud:Enabled>'
      print '        <vcloud:ChangeSid>false</vcloud:ChangeSid>'
      print '        <vcloud:VirtualMachineId>8908ba84-2c0d-48c4-a173-7918bd380544</vcloud:VirtualMachineId>'
      print '        <vcloud:JoinDomainEnabled>false</vcloud:JoinDomainEnabled>'
      print '        <vcloud:UseOrgSettings>false</vcloud:UseOrgSettings>'
      print '        <vcloud:AdminPasswordEnabled>true</vcloud:AdminPasswordEnabled>'
      print '        <vcloud:AdminPasswordAuto>true</vcloud:AdminPasswordAuto>'
      print '        <vcloud:ResetPasswordRequired>false</vcloud:ResetPasswordRequired>'
      print '        <vcloud:ComputerName>centos7-001</vcloud:ComputerName>'
      print '    </vcloud:GuestCustomizationSection>'

f.close()
